queue_rules:
  - name: default

pull_request_rules:
  - name: Queue Renovate PRs
    conditions:
      - author=renovate[bot]
      - check-success~=^test
      - check-success=lint
      - -draft
      # Optionally, require a label for more granular control:
      # - label=automerge
    actions:
      queue:
        name: default

  - name: Queue on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success~=^test
      - check-success=lint
      - -draft
    actions:
      queue:
        name: default
